### ISSUE TITLE
When running "python preprocess/preprocess_vod.py", An error has occurred"No module named 'utils.common'"

### ISSUE THREAD

**Issue by syh1620** [Toytiny/CMFlow#1]

**Comment by Toytiny** [comment]
Hi, thanks for reaching out. Please make sure there is a folder called 'utils' under 'preprocess/' before you import it into the preprocess_vod.py file.

**Comment by Toytiny** [comment]
And please pull the latest version of our repo to your local.

**Comment by syh1620** [comment]
> 嗨，感谢您伸出援手。在将“preprocess/”导入preprocess_vod.py文件之前，请确保在“preprocess/”下有一个名为“utils”的文件夹。

Yes.there is a folder named "utils" under "preprocess/".

**Comment by syh1620** [comment]
> And please pull the latest version of our repo to your local.

My environment configuration is Cuda 11.1 and pytorch 1.8.0, torchvison 0.9.0,torchaudio 0.8.0;Is it due to the environment configuration?

**Comment by Toytiny** [comment]
Your environmet config seems ok. Please try to change "from utils.common import get_frame_list" to "from .utils.common import get_frame_list" in preprocess.py before you run.

**Comment by syh1620** [comment]
> Your environmet config seems ok. Please try to change "from utils.common import get_frame_list" to "from .utils.common import get_frame_list" in preprocess.py before you run.
Sorry, this modification didn't work

**Comment by syh1620** [comment]
I solved the problem by creating a new __init__.py file in the "preprocess/utils" folder. Thanks

**Comment by syh1620** [comment]
But when I rerun the code, I get a RuntimeError:CUDA out of memory. I changed the size of the batch size in the RAFT/ train.py file, but it doesn't fix the problem

**Comment by Toytiny** [comment]
We didn't train the RAFT model in our code. Instead, we use its off-the-shelf pretrained model "raft-small". How much memory does your GPU have? At least 12 GB is needed to run the inference step of RAFT.

**Comment by Toytiny** [comment]
If you want to reduce the memory consumption, please change the parameter RESIZE_SCALE TO 1/2 in https://github.com/Toytiny/CMFlow/blob/master/preprocess/utils/global_param.py. It will downsample the input image by 1/2 and upsample the optical flow result back after inference.

**Comment by syh1620** [comment]
> We didn't train the RAFT model in our code. Instead, we use its off-the-shelf pretrained model "raft-small". How much memory does your GPU have? At least 12 GB is needed to run the inference step of RAFT.
My GPU memory is 12050MiB, which is about 12GB.

**Comment by syh1620** [comment]
> If you want to reduce the memory consumption, please change the parameter RESIZE_SCALE TO 1/2 in https://github.com/Toytiny/CMFlow/blob/master/preprocess/utils/global_param.py. It will downsample the input image by 1/2 and upsample the optical flow result back after inference.

It's working, thank you.

**Comment by Toytiny** [comment]
No problem. The generated optical flow from downsampled images may not be as good as the original settings. But it's ok. It will affect our model training as lot.

**Comment by Toytiny** [comment]
> I solved the problem by creating a new **init**.py file in the "preprocess/utils" folder. Thanks

Cool. We will also add a new init.py in that folder.

**Comment by syh1620** [comment]
I would like to ask what the phrI would like to ask what the phrase"We recommend copying the pose information from the closest later frame to frames lacking pose information."means?I do have the problem of "list index out of range"

**Comment by syh1620** [comment]
when l evaluate the trained CMFlow (or RaFlow) models on the test set:
python main.py --eval --dataset_path $DATA_PATH$ --exp_name $EXP_NAME$ --model cmflow (raflow)
I got this error: in the main.py file, line 75 net.eval() here, AttributeError: 'NoneType' object has no attribute 'eval '

**Comment by syh1620** [comment]
Hi, is there a visualisation tool to visualise the .json file in the results from test. I would like to see some radar points cast onto the image.
