### ISSUE TITLE
Vehicle Ego Velocity

### ISSUE THREAD

**Issue by paaraujo** [Toytiny/CMFlow#11]
Hello @Toytiny, I am trying to use the VoD dataset and the owner of the other repository suggested to come here ([post](https://github.com/tudelft-iv/view-of-delft-dataset/issues/59#issuecomment-1680850655)).

My case is simple, I need to compute the forward speed of the vehicle. Is there any piece of code in this repository that does this?

Thank you,
Paulo Araujo

**Comment by Toytiny** [comment]
Hi Paulo,

We don't compute the vehicle speed in my codes but we do extract the vehicle odometry (or ego-motion transform). Please refer to [https://github.com/Toytiny/CMFlow/blob/16a095a250453b4fe1363e4ec9dddd20d0d64e4f/preprocess/utils/get_flow_samples.py#L89C46-L89C58](https://github.com/Toytiny/CMFlow/blob/16a095a250453b4fe1363e4ec9dddd20d0d64e4f/preprocess/utils/get_flow_samples.py#L89C46-L89C58). Given the inter-frame vehicle transform, you can easily compute the vehicle forward speed.

If our codes help your work, please kindly cite our paper

Best,

Fangqiang
