### ISSUE TITLE
About discontinuous frames

### ISSUE THREAD

**Issue by EricLiuhhh** [Toytiny/CMFlow#12]
Hello! Thank you for your excellent work. I notice that the input to the CMFlow network does not involve a time interval between two frames. And the training data also involves only two consecutive frames. My question is does the network still perform well when I input two frames that are discontinuous but close in time, e.g. frame 00000 and frame 00005. I'm sorry if I missed any details.

**Comment by Toytiny** [comment]
Thanks for your interest in our work! As you said, we do not assume the time interval between two frames is known and fixed. Our training objective to make the network being able to infer the scene flow given any two radar point clouds close in time. I believe that our method can generalize to different time intervals well. However, we didn't prove this in our experiments. We encourage our users to validate this themselves according to their specific needs.

**Comment by EricLiuhhh** [comment]
Thank you for your reply, I will conduct experiments to observe the results.
