### ISSUE TITLE
When running "python preprocess/preprocess_vod.py",I did not create"label_track_gt",but it can run

### ISSUE THREAD

**Issue by kangnn** [Toytiny/CMFlow#13]
![image](https://github.com/Toytiny/CMFlow/assets/77667172/7364dd9a-9eb8-46d5-862f-4a8805540584)
#my command:
python preprocess/preprocess_vod.py --root_dir ./view_of_delft_PUBLIC --save_dir processed
When I encounted the issue:
File ".../preprocess/utils/vod/frame/transformations.py", line 277, in get_world_transform
t_odom_camera = np.array(jsons[0]["odomToCamera"], dtype=np.float32).reshape(4, 4)
IndexError: list index out of range
I changed the code 👍 in tranformations.py:
   

def get_world_transform(self):
        try:
            pose_file = os.path.join(self.frame_data_loader.kitti_locations.pose_dir,
                                 f'{self.frame_data_loader.frame_number}.json')
        except FileNotFoundError:
            logging.error(f"{self.frame_data_loader.frame_number}.json does not exist at"
                      f" location: {self.frame_data_loader.kitti_locations.pose_dir}!")
            return None, None, None
        jsons = []
        for line in open(pose_file, 'r'):
            jsons.append(json.loads(line))

        #print(f"Read {len(jsons)} lines from JSON file.")

        for i, frame_json in enumerate(jsons):
            #print(f"Checking line {i}: {frame_json}")
            if "odomToCamera" in frame_json:
                #print("Found valid 'odomToCamera' data.")
                t_odom_camera = np.array(frame_json["odomToCamera"], dtype=np.float32).reshape(4, 4)
                t_map_camera = np.eye(4)
                t_utm_camera = np.eye(4)
                return t_odom_camera, t_map_camera, t_utm_camera

        logging.error("No valid 'odomToCamera' pose information found in JSON file.")
        return None, None, None
and change the code in get_flow_samples.py:
      

# coordinate frame transformation from radar1 to radar2
        odom_cam_1 = transforms1.t_odom_camera
        odom_cam_2 = transforms2.t_odom_camera
        cam_radar_1 = transforms1.t_camera_radar
        cam_radar_2 = transforms2.t_camera_radar
        # 检查转换矩阵是否为None
        if odom_cam_1 is None or odom_cam_2 is None or cam_radar_1 is None or cam_radar_2 is None:
            logging.error(f"One of the required transformation matrices is None for frames {frame1} and {frame2}")
            return  # 跳过当前样本的处理

**Comment by Toytiny** [comment]
Hi Mahonehan,

Thanks for your interest in our work! For your issue, please see our explanation on possible errors during preprocessing in: https://github.com/Toytiny/CMFlow/blob/master/src/GETTING_STARTED.md#2-data-preprocess

**Comment by kangnn** [comment]
> Hi Mahonehan,
> 
> Thanks for your interest in our work! For your issue, please see our explanation on possible errors during preprocessing in: https://github.com/Toytiny/CMFlow/blob/master/src/GETTING_STARTED.md#2-data-preprocess

So,what can i do,when i encounter the 
i. Error when FrameDataLoader reads frame pose information.
File ".../preprocess/utils/vod/frame/transformations.py", line 277, in get_world_transform
t_odom_camera = np.array(jsons[0]["odomToCamera"], dtype=np.float32).reshape(4, 4)
IndexError: list index out of range

How to change the code?
Thanks advance!

**Comment by Toytiny** [comment]
You don't have to change the code, jus the following instructions in the link I provided:

![image](https://github.com/Toytiny/CMFlow/assets/42762086/f99acefb-d329-4825-abe0-12aaeccdf4d4)

**Comment by kangnn** [comment]
When I encounter the
![image](https://github.com/Toytiny/CMFlow/assets/77667172/e9aa6015-5194-4e4e-ae96-dbae9af0ef01)
The program terminated. What should I do next?
Also, Toytiny, can you provide the dataset download link? There might be an issue with the dataset I have. I applied for the link from the official source for a long time but haven't received it yet. In the end, I downloaded a dataset that I'm not sure if it's official.
> You don't have to change the code, jus the following instructions in the link I provided:
> 
> ![image](https://private-user-images.githubusercontent.com/42762086/296766241-f99acefb-d329-4825-abe0-12aaeccdf4d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjUwMTAsIm5iZiI6MTcwNTMyNDcxMCwicGF0aCI6Ii80Mjc2MjA4Ni8yOTY3NjYyNDEtZjk5YWNlZmItZDMyOS00ODI1LWFiZTAtMTJhYWVjY2RmNGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEzMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MzUxZTQ1OWI3OWE3MzgxMzEwYWMwZDFkNDYwMmJkNGUwOWRiZDExMDIyNzFlOWMzZTgxMDQxNzQ3OWQ0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6PhnFWZU8JtxvLTCGXto9WQ47xceveRsdy1f1qcHis8)

**Comment by Toytiny** [comment]
When the program terminated, you can follow the instruction we give below to solve the problem and run again. 

Sorry, we cannot provide the dataset download link under the usage license. Please contact Andras Palffy or Dariu Gavilla for the download issue.

**Comment by kangnn** [comment]
> When the program terminated, you can follow the instruction we give below to solve the problem and run again.
> 
> Sorry, we cannot provide the dataset download link under the usage license. Please contact Andras Palffy or Dariu Gavilla for the download issue.

Thanks，I will try.
