### ISSUE TITLE
VoD preprocessing results in gt_mask being only 1.0

### ISSUE THREAD

**Issue by LeonSchw** [Toytiny/CMFlow#16]
I want to take your previous approach RaFlow as a baseline for my master thesis on self-supervised moving object segmentation of radar point clouds. During evaluation of the models provided in the repo I found that the results were suspicious in the sense that the moving IoU of the vod model was exactly zero. Upon further inspection I found that the gt_masks against which the results are measured only contain ones meaning every point is considered static. This can't be correct since the original dataset explicitly contains moving objects.

Is there any way you could help me find the error in the preprocessing?

**Comment by Toytiny** [comment]
Hi, could you visualize and observe the gt_masks for more frames? Did you use our provided code to generate the gt_masks?

**Comment by LeonSchw** [comment]
For generation of the export I simply followed the instructions in the `GETTING_STARTED.md`.

I iterated through all the exported pairs and counted the ones where the gt_masks only contained ones. This number of pair is exactly the size of the respective partition. Please find the code for this in the attached zip-file.
[VoD_inspection.zip](https://github.com/user-attachments/files/16968522/VoD_inspection.zip)

**Comment by Toytiny** [comment]
Hi, could you show me which frames only contained ones in their gt_masks. Note that for our training samples, we do not generate gt_masks as our method rely on cross-modal supervision signals.

**Comment by LeonSchw** [comment]
The distinction between train, val and test is clear. For the training samples the groundtruth masks and labels are zero since for training of CMFlow the pse ones are used. But actually for every single sample in the validation and test partition the gt_masks seem to be only ones.

**Comment by Toytiny** [comment]
Hi, could you try some debugging to find out from which step the generation of gt_masks becomes abnormal? I think this should help to solve your problem as our users could succesfully generate valid gt_masks and reproduce our results.
