### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by JiaNing-Z** [Toytiny/CMFlow#6]
![2023-07-16 11-50-52屏幕截图](https://github.com/Toytiny/CMFlow/assets/87583456/f6ac24ad-812a-404a-886d-c53aed8e558e)
Hello, use the weights in the file for testing, but the effect does not reach the ideal state.

**Comment by Toytiny** [comment]
Is the plot derived from the model cmflow or cmflow_t?

**Comment by JiaNing-Z** [comment]
cmflow

**Comment by Toytiny** [comment]
Hi, to draw the same plot as in our paper (i.e. Fig.  7), please use the model in "cmflow_t_ed_cvpr/models/" that is uploaded today. The command is "python main.py --eval --dataset_path DATA_PATH --exp_name cmflow_t_ed_cvpr --model cmflow_t --dataset vodClipDataset". 
This model can produce the result of row (e) in Table 4. Both temporal update and extra unannotated data are used for training it.   If you want to try your own model with the public part of VoD, please try to train the cmflow_t model, the command is "python main.py --dataset_path DATA_PATH --exp_name EXP_NAME  --model cmflow_t --dataset vodClipDataset ". Unfortunately, the extra unannotated part of VoD dataset we used is still confidential and will be released in the future.

**Comment by JiaNing-Z** [comment]
OK，thanks
