### ISSUE TITLE
About the trained CMFlow (T) model trained with extra unannotated data

### ISSUE THREAD

**Issue by xlbjy** [Toytiny/CMFlow#7]
Hi, can you provide the training details of the trained CMFlow (T) model trained with extra unannotated data? or provide the training command in readme? Thank you very much.

**Comment by Toytiny** [comment]
Hi, unfortunately, the extra part of unannotated data is currently unavailable. You may need to contact the VoD authors for it. Training with extra unannotated data is similar to our "regular" ones. You only need to add preprocessed samples to your data path.
