### ISSUE TITLE
Difference on performance

### ISSUE THREAD

**Issue by FengyeXZ** [Toytiny/CMFlow#8]
I have run the experiment on my local machine with the default evironment and settings. The test results I got from RaFlow and CMFlow(T) are pretty decent(under 10% error). However, for the result got from CMFlow(default setting: batch size 16), I got some errors over 15-20% on scores. After that, I use the batch size 8 to train the CMFlow again, I got an improved performance(error within 10%). 

I want to know what make the difference on CMFlow but not in RaFlow or CMFlow(T)?

**Comment by Toytiny** [comment]
Dear user,

thanks for your inquiry. The difference on performance is normal and may come from the quality of generated optical labels, the randomness in data loading, the training epoch and batch size. We recommend you use a smaller batch size and more training epochs to obtain a better performance. Don’t worry about the difference, 10% is acceptable to report our results.

**Comment by FengyeXZ** [comment]
Hi,
Thanks for your reply. The difference on performance of CMFlow seems greater than other two models. Is this normal? What could be the reasons that result this?

Many thanks,
Shang

**Comment by Toytiny** [comment]
Hi,

It should be normal. Just run multiple experiments and select the model
that is sufficiently trained or adopt the mean results across them.

**Comment by FengyeXZ** [comment]
Cheers
